[package]
name = "oc-sim"
description = "Native simulator and terminal UI for the Ornament & Crime Rust firmware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
oc-core.workspace = true
ratatui.workspace = true

[lints]
workspace = true
