[package]
name = "oc-drivers"
description = "Peripheral drivers for the Ornament & Crime module, generic over embedded-hal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
oc-core.workspace = true
embedded-hal.workspace = true

[lints]
workspace = true
